version: '3'
services:
  rotating-proxy:
    build: .
    image: "brianstech/docker-rotating-proxy:latest"
    environment:
      NUM_PROXIES: 30
    ports:
      - "8080:8080"
      - "4444:4444"
    volumes:
      - "./:/haproxy"
